---

- name: Install essential packages
  tags:
    - docker
  package:
    name: "{{ essential_packages }}"
    state: latest

- name: Add Docker apt-key
  tags:
    - docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker repo
  tags:
    - docker
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
  notify: apt update

- name: Install Docker
  tags:
    - docker
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes

- name: Add docker User Permissions
  tags:
    - docker
  shell: "usermod -aG docker {{ username }}"


